name: ci

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Build site
        run: deno run -A https://deno.land/x/lume@v1.5.1/ci.ts

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: kevin-raimbaud
          entrypoint: server/main.ts